import type { GlossaryTerm } from './types';

const glossaryTerms: GlossaryTerm[] = [
  {
    term: '주대',
    reading: 'judae',
    definition: '룸 이용 기본 요금을 뜻하는 업계 용어입니다. 룸살롱, 하이퍼블릭 등에서 방을 사용하는 대가로 지불하는 기본 비용으로, 주류비와는 별도로 청구됩니다. 업소 등급과 지역에 따라 금액 차이가 크며, 보통 시간 단위로 책정됩니다.',
    relatedVenues: ['roomsalon', 'highpublic', 'shirtsroom', 'kimonoroom'],
    relatedPageSlugs: ['price', 'how-to-use'],
  },
  {
    term: 'TC',
    reading: '티씨',
    definition: 'Table Charge의 약자로, 테이블에 앉는 인원 수에 따라 1인당 부과되는 요금입니다. 주대와는 별개로 추가되며, 주로 하이퍼블릭이나 룸살롱에서 적용됩니다. TC에는 기본 안주와 세팅비가 포함되는 경우가 많습니다.',
    relatedVenues: ['roomsalon', 'highpublic', 'shirtsroom'],
    relatedPageSlugs: ['price'],
  },
  {
    term: '세트',
    reading: 'seteu',
    definition: '주류와 안주, 서비스를 묶어 제공하는 패키지 상품입니다. 양주 1병 + 안주 + 기본 서비스가 포함된 세트 메뉴가 일반적이며, 개별 주문보다 가격이 저렴한 경우가 많습니다. 업소마다 세트 구성이 다르므로 사전 확인이 필요합니다.',
    relatedVenues: ['roomsalon', 'highpublic', 'shirtsroom', 'kimonoroom'],
    relatedPageSlugs: ['price', 'how-to-use'],
  },
  {
    term: '폭탄주',
    reading: 'poktan-ju',
    definition: '맥주잔에 소주잔을 빠뜨려 만드는 한국식 칵테일입니다. 소맥(소주+맥주), 고진감래 등 다양한 변형이 있으며, 한국 유흥 문화의 대표적인 음주 방식입니다. 빠르게 취하는 효과가 있어 건배 시 자주 활용되지만, 음주량 조절에 주의가 필요합니다.',
    relatedVenues: ['karaoke', 'highpublic', 'roomsalon'],
    relatedPageSlugs: ['how-to-use', 'etiquette'],
  },
  {
    term: '런닝타임',
    reading: 'running time',
    definition: '업소에서 서비스가 제공되는 기본 이용 시간을 뜻합니다. 일반적으로 룸살롱은 2시간, 하이퍼블릭은 2~3시간이 기본 런닝타임이며, 추가 시간 이용 시 연장 요금이 부과됩니다. 업소에 따라 런닝타임이 다르므로 입장 전 확인하는 것이 좋습니다.',
    relatedVenues: ['roomsalon', 'highpublic', 'shirtsroom', 'kimonoroom'],
    relatedPageSlugs: ['price', 'how-to-use'],
  },
  {
    term: '마담',
    reading: 'madam',
    definition: '업소의 여성 매니저 또는 총괄 관리자를 가리키는 호칭입니다. 고객 응대, 직원 관리, 서비스 조율 등 업소 운영 전반을 담당하며, 마담의 역량에 따라 업소의 서비스 품질이 크게 좌우됩니다. 경험 많은 마담일수록 고객 취향 파악이 빠르고 만족도가 높습니다.',
    relatedVenues: ['roomsalon', 'highpublic', 'shirtsroom', 'kimonoroom'],
    relatedPageSlugs: ['how-to-use'],
  },
  {
    term: '웨이터',
    reading: 'waiter',
    definition: '남성 서빙 직원으로, 주류 서빙, 룸 세팅, 고객 안내 등을 담당합니다. 호스트바에서는 고객을 접대하는 남성 직원을 가리키기도 합니다. 업소에 따라 웨이터의 역할과 복장이 다르며, 고급 업소일수록 체계적인 서비스 교육을 받은 웨이터가 근무합니다.',
    relatedVenues: ['roomsalon', 'highpublic', 'hostbar'],
    relatedPageSlugs: ['how-to-use', 'etiquette'],
  },
  {
    term: '초이스',
    reading: 'choice',
    definition: '룸살롱이나 하이퍼블릭에서 함께할 파트너(접대 직원)를 직접 선택하는 과정을 뜻합니다. 일렬로 서거나 프로필을 보고 선택하는 방식이 일반적이며, 업소마다 초이스 방식이 다릅니다. 초이스에 추가 비용이 부과되는 경우도 있으니 사전에 확인이 필요합니다.',
    relatedVenues: ['roomsalon', 'highpublic', 'shirtsroom', 'kimonoroom'],
    relatedPageSlugs: ['how-to-use', 'etiquette'],
  },
  {
    term: '2차',
    reading: 'icha',
    definition: '첫 번째 모임 장소(1차, 주로 식사)를 마친 후 이동하는 두 번째 장소를 뜻합니다. 한국 유흥 문화에서 2차는 보통 노래방, 하이퍼블릭, 바 등으로 이동하는 것을 의미하며, 한 밤에 여러 장소를 돌아다니는 것이 일반적인 한국식 유흥 패턴입니다.',
    relatedVenues: ['karaoke', 'highpublic', 'roomsalon'],
    relatedPageSlugs: ['how-to-use'],
  },
  {
    term: '3차',
    reading: 'samcha',
    definition: '2차를 마친 후 세 번째로 이동하는 장소입니다. 보통 노래방이나 포장마차, 라면집 등 마무리 성격의 장소가 많습니다. 3차까지 이어지는 모임은 분위기가 매우 좋거나 특별한 날인 경우가 많으며, 건강과 컨디션을 고려해 적절히 마무리하는 것이 좋습니다.',
    relatedVenues: ['karaoke', 'highpublic'],
    relatedPageSlugs: ['how-to-use'],
  },
  {
    term: '풀살롱',
    reading: 'pul-salon',
    definition: '풀(Full) 서비스를 제공하는 고급 룸살롱을 뜻합니다. 일반 룸살롱보다 서비스 범위가 넓고 가격대가 높으며, VIP 고객 대상의 프리미엄 서비스를 제공합니다. 철저한 프라이버시 보장과 최상급 서비스가 특징이며, 대부분 예약제로 운영됩니다.',
    relatedVenues: ['roomsalon'],
    relatedPageSlugs: ['how-to-use', 'price'],
  },
  {
    term: '하드코어',
    reading: 'hardcore',
    definition: '서비스 강도가 높은 업소 스타일을 비공식적으로 가리키는 표현입니다. 주로 룸살롱이나 유흥업소에서 보다 적극적이고 밀착된 서비스를 제공하는 경우를 뜻하며, 업소마다 세부적인 서비스 내용은 다릅니다. 하드코어 스타일의 업소는 가격대가 높은 편입니다.',
    relatedVenues: ['roomsalon', 'shirtsroom'],
    relatedPageSlugs: ['how-to-use'],
  },
  {
    term: '소프트',
    reading: 'soft',
    definition: '서비스 강도가 낮고 부드러운 스타일의 업소를 뜻합니다. 대화와 음주를 중심으로 한 편안한 분위기가 특징이며, 처음 방문하는 고객이나 가벼운 모임에 적합합니다. 하이퍼블릭이나 셔츠룸에서 많이 볼 수 있는 스타일입니다.',
    relatedVenues: ['highpublic', 'shirtsroom'],
    relatedPageSlugs: ['how-to-use'],
  },
  {
    term: '부킹',
    reading: 'booking',
    definition: '원래는 나이트클럽에서 웨이터가 남녀 테이블을 연결해주는 것을 뜻하지만, 유흥업소에서는 넓은 의미로 예약이나 사전 준비를 가리킵니다. 인기 있는 업소는 당일 방문 시 자리가 없는 경우가 많으므로, 미리 부킹(예약)하는 것이 필수입니다.',
    relatedVenues: ['highpublic', 'roomsalon', 'karaoke'],
    relatedPageSlugs: ['how-to-use'],
  },
  {
    term: '텐프로',
    reading: 'ten-pro',
    definition: '10%를 의미하는 용어로, 업소에서 서비스 수준이 상위 10%에 해당하는 프리미엄 등급을 뜻합니다. 텐프로 업소는 직원의 외모, 서비스 마인드, 시설 등 모든 면에서 최상위권이며, 가격대도 그에 상응하게 높습니다. 분당 서현역 일대에 텐프로급 업소가 다수 있습니다.',
    relatedVenues: ['roomsalon', 'highpublic'],
    relatedPageSlugs: ['ranking', 'price'],
  },
  {
    term: '퍼블릭',
    reading: 'public',
    definition: '하이퍼블릭의 줄임말로, 퍼블릭 룸 형태의 유흥업소를 가리킵니다. 개별 룸에서 파트너와 함께 음주와 대화를 즐기는 형태로, 룸살롱보다 캐주얼하고 가격이 합리적입니다. 하이퍼블릭은 퍼블릭의 상위 버전으로 이해할 수 있습니다.',
    relatedVenues: ['highpublic'],
    relatedPageSlugs: ['how-to-use', 'price'],
  },
  {
    term: '가라오케',
    reading: 'karaoke',
    definition: '일본어에서 유래한 노래방을 뜻하는 용어입니다. 한국에서는 일반 노래방, 코인노래방, 프리미엄 노래방 등 다양한 형태가 있으며, 유흥 문화에서 2차·3차 장소로 가장 많이 이용됩니다. 최근에는 음향과 인테리어를 고급화한 프리미엄 노래방이 인기를 끌고 있습니다.',
    relatedVenues: ['karaoke'],
    relatedPageSlugs: ['how-to-use', 'price'],
  },
  {
    term: '양주',
    reading: 'yangju',
    definition: '위스키, 브랜디, 보드카 등 서양 증류주를 통칭하는 한국식 표현입니다. 유흥업소에서 양주는 주요 수익원이자 고객 서비스의 핵심 요소로, 업소마다 취급하는 양주 브랜드와 가격이 다릅니다. 고급 업소일수록 프리미엄 양주 라인업이 다양합니다.',
    relatedVenues: ['roomsalon', 'highpublic', 'shirtsroom', 'kimonoroom'],
    relatedPageSlugs: ['price', 'how-to-use'],
  },
  {
    term: '룸',
    reading: 'room',
    definition: '유흥업소에서 고객이 이용하는 개별 공간(방)을 뜻합니다. 룸의 크기, 인테리어, 음향 장비 등에 따라 가격이 달라지며, VIP 룸·스탠다드 룸·대형 룸 등 등급이 나뉘는 곳도 있습니다. 룸 선택은 이용 만족도에 큰 영향을 미칩니다.',
    relatedVenues: ['karaoke', 'roomsalon', 'highpublic', 'shirtsroom', 'kimonoroom'],
    relatedPageSlugs: ['price', 'how-to-use'],
  },
  {
    term: '도우미',
    reading: 'doumi',
    definition: '유흥업소에서 고객 옆에서 음주와 대화를 함께하는 접대 직원을 가리키는 표현입니다. 업소 유형에 따라 역할과 서비스 범위가 다르며, 룸살롱·하이퍼블릭·셔츠룸 등에서 근무합니다. 도우미의 서비스 수준은 업소 등급에 크게 좌우됩니다.',
    relatedVenues: ['roomsalon', 'highpublic', 'shirtsroom', 'kimonoroom'],
    relatedPageSlugs: ['how-to-use', 'etiquette'],
  },
  {
    term: '접대',
    reading: 'jeopdae',
    definition: '비즈니스 목적으로 거래처나 상사를 유흥업소에 초대하여 대접하는 행위를 뜻합니다. 한국 비즈니스 문화에서 접대는 관계 구축의 중요한 수단이며, 룸살롱이나 고급 하이퍼블릭이 접대 장소로 많이 이용됩니다. 접대비 지출에 대한 세무 규정도 있으니 주의가 필요합니다.',
    relatedVenues: ['roomsalon', 'highpublic'],
    relatedPageSlugs: ['how-to-use', 'etiquette'],
  },
  {
    term: '보틀',
    reading: 'bottle',
    definition: '양주를 병(보틀) 단위로 주문하는 것을 뜻합니다. 보틀 키핑은 다 마시지 못한 양주를 업소에 보관해두는 서비스로, 단골 고객이 자주 이용합니다. 보틀 가격은 시중 판매가의 2~5배가 일반적이며, 업소 등급에 따라 차이가 큽니다.',
    relatedVenues: ['roomsalon', 'highpublic', 'shirtsroom'],
    relatedPageSlugs: ['price'],
  },
  {
    term: '보틀키핑',
    reading: 'bottle keeping',
    definition: '업소에서 다 마시지 못한 양주 병을 보관해두는 서비스입니다. 일정 기간(보통 1~3개월) 보관해주며, 다음 방문 시 보관된 양주를 이어서 마실 수 있습니다. 단골 고객에게 제공되는 혜택으로, 보틀키핑을 이용하면 장기적으로 비용을 절약할 수 있습니다.',
    relatedVenues: ['roomsalon', 'highpublic'],
    relatedPageSlugs: ['price', 'how-to-use'],
  },
  {
    term: '영업시간',
    reading: 'yeongeopsiigan',
    definition: '업소의 운영 시간을 뜻합니다. 대부분의 유흥업소는 오후 6~7시에 영업을 시작해 새벽 4~5시까지 운영합니다. 노래방은 낮 시간부터 이른 아침까지 운영하는 곳이 많습니다. 금요일·토요일은 영업 종료 시간이 더 늦어지는 경우가 많습니다.',
    relatedVenues: ['karaoke', 'highpublic', 'roomsalon', 'hostbar', 'shirtsroom', 'kimonoroom'],
    relatedPageSlugs: ['how-to-use'],
  },
  {
    term: '입장료',
    reading: 'ipjangnyo',
    definition: '업소에 입장할 때 지불하는 기본 요금입니다. 노래방은 시간당 요금, 클럽은 입장료, 룸살롱·하이퍼블릭은 주대 형태로 부과됩니다. 업소에 따라 입장료에 음료 1잔이 포함되는 경우도 있습니다.',
    relatedVenues: ['karaoke', 'highpublic', 'roomsalon'],
    relatedPageSlugs: ['price'],
  },
  {
    term: '팁',
    reading: 'tip',
    definition: '서비스에 대한 감사의 표시로 추가 지불하는 금액입니다. 한국 유흥업소에서 팁은 필수는 아니지만, 특별한 서비스를 받았거나 만족도가 높을 때 자발적으로 제공하는 문화가 있습니다. 팁을 주면 다음 방문 시 더 좋은 서비스를 기대할 수 있습니다.',
    relatedVenues: ['roomsalon', 'highpublic', 'hostbar', 'shirtsroom'],
    relatedPageSlugs: ['etiquette', 'price'],
  },
  {
    term: '단체석',
    reading: 'danchesik',
    definition: '10인 이상 대규모 모임을 위한 넓은 공간을 뜻합니다. 대형 노래방이나 하이퍼블릭에서 제공하며, 회사 회식이나 동창회 등에 많이 이용됩니다. 단체석은 사전 예약이 필수이며, 단체 할인 패키지를 제공하는 곳도 있습니다.',
    relatedVenues: ['karaoke', 'highpublic'],
    relatedPageSlugs: ['how-to-use', 'price'],
  },
  {
    term: '노래방 기계',
    reading: 'noraebang gigye',
    definition: '노래방에서 사용하는 음악 재생 기기입니다. 한국의 대표적인 노래방 기계 브랜드로는 TJ미디어와 금영(KY)이 있으며, 곡 목록과 음향 특성이 다릅니다. 최근에는 AI 채점, 녹음 기능, 뮤직비디오 재생 등 첨단 기능이 탑재된 기계가 많습니다.',
    relatedVenues: ['karaoke'],
    relatedPageSlugs: ['how-to-use'],
  },
  {
    term: '번호판',
    reading: 'beonhopan',
    definition: '초이스 과정에서 직원에게 부여되는 식별 번호를 뜻합니다. 고객이 직접 이름 대신 번호로 선택할 수 있도록 한 시스템으로, 프라이버시 보호 차원에서 운영됩니다. 업소에 따라 사진과 프로필을 함께 제공하는 곳도 있습니다.',
    relatedVenues: ['roomsalon', 'highpublic', 'shirtsroom'],
    relatedPageSlugs: ['how-to-use'],
  },
  {
    term: '서비스',
    reading: 'service',
    definition: '업소에서 무료로 제공하는 추가 혜택을 뜻하는 한국식 표현입니다. 서비스 과일, 서비스 안주, 서비스 음료 등 형태가 다양하며, 단골 고객이나 대규모 이용 시 더 많은 서비스가 제공되는 경향이 있습니다. 업소의 서비스 수준은 재방문 결정에 큰 영향을 미칩니다.',
    relatedVenues: ['karaoke', 'highpublic', 'roomsalon', 'shirtsroom', 'kimonoroom'],
    relatedPageSlugs: ['how-to-use', 'etiquette'],
  },
  {
    term: '콜',
    reading: 'call',
    definition: '전화나 메신저로 업소에 방문 의사를 알리거나 예약하는 행위를 뜻합니다. 인기 업소는 콜 없이 방문하면 대기가 길어질 수 있으므로, 사전 콜이 필수입니다. 또한 특정 도우미를 지정 콜하는 것도 가능한 업소가 있습니다.',
    relatedVenues: ['roomsalon', 'highpublic', 'shirtsroom'],
    relatedPageSlugs: ['how-to-use'],
  },
  {
    term: '아가씨',
    reading: 'agassi',
    definition: '유흥업소에서 여성 접대 직원을 가리키는 비공식적 표현입니다. 업소 유형에 따라 역할과 서비스 범위가 다르며, 최근에는 보다 존중하는 표현의 사용이 권장되고 있습니다. 공식적으로는 "직원", "파트너" 등의 표현이 사용됩니다.',
    relatedVenues: ['roomsalon', 'highpublic', 'shirtsroom', 'kimonoroom'],
    relatedPageSlugs: ['etiquette'],
  },
  {
    term: '실장',
    reading: 'siljang',
    definition: '업소의 현장 관리자 또는 영업 담당자를 가리킵니다. 실장은 고객 유치, 룸 배정, 서비스 관리 등을 담당하며, 단골 고객과의 관계 유지에서 핵심적인 역할을 합니다. 좋은 실장을 통해 방문하면 더 나은 서비스와 가격을 제공받을 수 있습니다.',
    relatedVenues: ['roomsalon', 'highpublic', 'shirtsroom'],
    relatedPageSlugs: ['how-to-use'],
  },
  {
    term: '프리미엄',
    reading: 'premium',
    definition: '일반 등급보다 높은 상위 서비스 등급을 뜻합니다. 프리미엄 업소는 인테리어, 주류, 직원 수준 등 모든 면에서 최상의 품질을 제공하며, 그만큼 가격대도 높습니다. 분당 서현역 일대에 프리미엄급 업소가 다수 위치하고 있습니다.',
    relatedVenues: ['karaoke', 'roomsalon', 'highpublic'],
    relatedPageSlugs: ['ranking', 'price'],
  },
  {
    term: '셔츠룸',
    reading: 'shirts room',
    definition: '직원이 셔츠(와이셔츠) 차림으로 서비스를 제공하는 업소 형태입니다. 룸살롱과 유사하지만, 좀 더 캐주얼하고 편안한 분위기가 특징이며, 가격대도 룸살롱보다 합리적입니다. 셔츠룸은 직장인 소규모 모임에서 인기가 높습니다.',
    relatedVenues: ['shirtsroom'],
    relatedPageSlugs: ['how-to-use', 'price'],
  },
  {
    term: '기모노룸',
    reading: 'kimono room',
    definition: '직원이 일본 전통 의상인 기모노를 착용하고 서비스를 제공하는 업소입니다. 일식 콘셉트의 실내 장식과 함께 독특한 분위기를 연출하며, 룸살롱의 변형된 형태로 볼 수 있습니다. 기모노룸은 희소성이 높아 특별한 자리에서 주로 이용됩니다.',
    relatedVenues: ['kimonoroom'],
    relatedPageSlugs: ['how-to-use', 'price'],
  },
  {
    term: '호스트바',
    reading: 'host bar',
    definition: '남성 직원(호스트)이 여성 고객을 접대하는 유흥업소입니다. 여성 고객이 마음에 드는 호스트를 선택하여 음주와 대화를 즐기는 형태로, 룸살롱의 성별 역전 버전이라 할 수 있습니다. 분당에서도 소수의 호스트바가 운영되고 있으며, 여성 고객 전용 공간입니다.',
    relatedVenues: ['hostbar'],
    relatedPageSlugs: ['how-to-use', 'price'],
  },
  {
    term: '하이퍼블릭',
    reading: 'high public',
    definition: '퍼블릭(public)의 상위 버전으로, 고급화된 룸형 유흥업소를 뜻합니다. 일반 퍼블릭보다 인테리어, 서비스, 직원 수준이 높으며, 룸살롱보다는 캐주얼한 분위기입니다. 가격도 룸살롱과 퍼블릭의 중간 수준으로, 가성비가 좋아 인기가 높습니다.',
    relatedVenues: ['highpublic'],
    relatedPageSlugs: ['how-to-use', 'price'],
  },
  {
    term: '연장',
    reading: 'yeonjang',
    definition: '기본 런닝타임을 초과하여 추가로 이용하는 것을 뜻합니다. 연장 시 추가 요금이 부과되며, 보통 30분~1시간 단위로 연장이 가능합니다. 연장 요금은 업소마다 다르므로, 이용 전에 미리 확인하는 것이 좋습니다. 분위기가 좋을 때 자연스럽게 연장이 이뤄지는 경우가 많습니다.',
    relatedVenues: ['roomsalon', 'highpublic', 'shirtsroom', 'kimonoroom'],
    relatedPageSlugs: ['price', 'how-to-use'],
  },
  {
    term: '안주',
    reading: 'anju',
    definition: '술과 함께 먹는 음식을 뜻하는 한국어 표현입니다. 유흥업소에서는 과일 플레이트, 마른안주, 디저트 등이 제공되며, 업소에 따라 안주 종류와 품질이 다릅니다. 고급 업소일수록 프리미엄 안주(한우 육회, 회 등)를 제공하는 경향이 있습니다.',
    relatedVenues: ['karaoke', 'highpublic', 'roomsalon', 'shirtsroom'],
    relatedPageSlugs: ['price', 'how-to-use'],
  },
  {
    term: '코인노래방',
    reading: 'coin noraebang',
    definition: '동전이나 카드를 넣어 곡 단위로 이용하는 소형 노래방입니다. 1곡당 500~1,000원으로 저렴하게 이용할 수 있어 가벼운 노래 연습이나 짧은 2차에 적합합니다. 인테리어와 음향은 일반 노래방보다 단순하지만, 부담 없이 즐길 수 있다는 장점이 있습니다.',
    relatedVenues: ['karaoke'],
    relatedPageSlugs: ['price', 'how-to-use'],
  },
  {
    term: '발렛',
    reading: 'valet',
    definition: '고객의 차량을 대신 주차해주는 서비스입니다. 고급 유흥업소에서 제공하는 경우가 많으며, 무료 또는 소정의 팁으로 이용할 수 있습니다. 분당 지역은 주차난이 심한 곳이 있어, 발렛 서비스가 있는 업소를 선택하면 편리합니다.',
    relatedVenues: ['roomsalon', 'highpublic'],
    relatedPageSlugs: ['how-to-use'],
  },
  {
    term: '대리운전',
    reading: 'daeri unjeon',
    definition: '음주 후 고객의 차량을 대신 운전해주는 서비스입니다. 카카오 대리, 로지 대리 등 앱을 통해 호출할 수 있으며, 분당 지역은 대리운전 수요가 많아 배차가 빠른 편입니다. 유흥업소 이용 후 안전한 귀가를 위해 대리운전 이용을 강력히 권장합니다.',
    relatedVenues: ['karaoke', 'highpublic', 'roomsalon', 'hostbar', 'shirtsroom', 'kimonoroom'],
    relatedPageSlugs: ['how-to-use'],
  },
  {
    term: '회식',
    reading: 'hoesik',
    definition: '회사 동료들이 함께 모여 식사하고 술을 마시는 한국 특유의 직장 문화입니다. 보통 1차 식사 → 2차 노래방 또는 유흥업소 → 3차 마무리의 패턴으로 진행됩니다. 분당은 IT 기업이 많아 팀 회식 수요가 매우 높으며, 업소들도 회식 패키지를 다양하게 제공합니다.',
    relatedVenues: ['karaoke', 'highpublic'],
    relatedPageSlugs: ['how-to-use'],
  },
  {
    term: '건배',
    reading: 'geonbae',
    definition: '술잔을 들어 축하나 건강을 기원하며 함께 마시는 행위입니다. 한국 음주 문화에서 건배는 매우 중요한 의례로, 윗사람이 건배를 제안하면 따르는 것이 예의입니다. 건배 시 연장자보다 잔을 낮추는 것이 한국식 예절입니다.',
    relatedVenues: ['karaoke', 'highpublic', 'roomsalon'],
    relatedPageSlugs: ['etiquette'],
  },
  {
    term: '원샷',
    reading: 'one shot',
    definition: '술잔의 내용물을 한 번에 비우는 것을 뜻합니다. 한국 음주 문화에서 원샷은 친밀감의 표현으로 자주 행해지지만, 강요해서는 안 되며 개인의 주량을 존중하는 것이 중요합니다. 폭탄주와 함께 원샷을 하는 것이 한국식 건배 문화의 특징입니다.',
    relatedVenues: ['karaoke', 'highpublic', 'roomsalon'],
    relatedPageSlugs: ['etiquette'],
  },
  {
    term: '마이크',
    reading: 'mike',
    definition: '노래방에서 노래를 부를 때 사용하는 마이크를 뜻합니다. 무선 마이크가 기본이며, 고급 노래방에서는 콘덴서 마이크 등 프로급 장비를 갖춘 곳도 있습니다. 마이크 위생도 중요한 요소로, 좋은 업소일수록 소독과 관리가 철저합니다.',
    relatedVenues: ['karaoke'],
    relatedPageSlugs: ['how-to-use'],
  },
  {
    term: '프라이빗 룸',
    reading: 'private room',
    definition: '다른 고객과 분리된 독립적인 공간을 뜻합니다. 방음이 잘 되어 있고 외부 시선이 차단되어, 비밀이 보장되어야 하는 비즈니스 접대나 프라이빗 모임에 적합합니다. VIP 프라이빗 룸은 별도의 입구와 화장실을 갖춘 곳도 있습니다.',
    relatedVenues: ['roomsalon', 'highpublic', 'karaoke'],
    relatedPageSlugs: ['price', 'how-to-use'],
  },
  {
    term: '웰컴드링크',
    reading: 'welcome drink',
    definition: '입장 시 무료로 제공되는 환영 음료입니다. 보통 칵테일이나 하우스 와인 형태로 제공되며, 고급 업소에서 고객 만족도를 높이기 위한 서비스입니다. 웰컴드링크가 제공되는 업소는 전반적인 서비스 수준이 높은 경향이 있습니다.',
    relatedVenues: ['roomsalon', 'highpublic'],
    relatedPageSlugs: ['how-to-use'],
  },
  {
    term: '지명',
    reading: 'jimyeong',
    definition: '특정 직원을 이름이나 번호로 지정하여 요청하는 것을 뜻합니다. 초이스와 유사하지만, 이전에 마음에 들었던 직원을 다시 요청할 때 주로 사용합니다. 지명 시 추가 비용이 발생하는 업소도 있으며, 인기 직원은 지명 경쟁이 치열할 수 있습니다.',
    relatedVenues: ['roomsalon', 'highpublic', 'shirtsroom'],
    relatedPageSlugs: ['how-to-use', 'price'],
  },
  {
    term: '체인지',
    reading: 'change',
    definition: '초이스한 직원이 마음에 들지 않을 때 다른 직원으로 교체를 요청하는 것입니다. 대부분의 업소에서 1~2회 체인지가 가능하며, 체인지에 추가 비용이 붙지 않는 것이 일반적입니다. 다만 너무 잦은 체인지는 예의에 어긋날 수 있으니 신중히 결정하는 것이 좋습니다.',
    relatedVenues: ['roomsalon', 'highpublic', 'shirtsroom'],
    relatedPageSlugs: ['how-to-use', 'etiquette'],
  },
  {
    term: '소맥',
    reading: 'somaek',
    definition: '소주와 맥주를 섞은 한국식 혼합 음료입니다. 소주와 맥주의 비율에 따라 맛이 달라지며, 보통 소주 3 : 맥주 7 비율이 가장 일반적입니다. 폭탄주의 기본 형태이며, 한국 유흥 문화에서 가장 대중적으로 소비되는 음주 방식 중 하나입니다.',
    relatedVenues: ['karaoke', 'highpublic', 'roomsalon'],
    relatedPageSlugs: ['how-to-use'],
  },
  {
    term: '다이스',
    reading: 'dice',
    definition: '술자리에서 사용하는 주사위 게임입니다. 다이스 게임은 술자리의 분위기를 띄우는 데 효과적이며, 진 사람이 벌칙(원샷 등)을 수행하는 방식으로 진행됩니다. 유흥업소에서는 기본 게임 도구로 다이스를 제공하는 곳이 많습니다.',
    relatedVenues: ['highpublic', 'roomsalon', 'shirtsroom'],
    relatedPageSlugs: ['how-to-use'],
  },
  {
    term: '쇼타임',
    reading: 'showtime',
    definition: '업소에서 제공하는 특별 공연이나 이벤트 시간을 뜻합니다. 마술, 댄스, 노래 공연 등 다양한 형태가 있으며, 고객의 흥을 돋우기 위한 서비스입니다. 쇼타임이 있는 업소는 엔터테인먼트 요소가 강해 처음 방문하는 고객에게도 즐거운 경험을 제공합니다.',
    relatedVenues: ['highpublic', 'roomsalon'],
    relatedPageSlugs: ['how-to-use'],
  },
];

export function getAllGlossaryTerms(): GlossaryTerm[] {
  return glossaryTerms;
}

export function getGlossaryTermsByVenue(venueId: string): GlossaryTerm[] {
  return glossaryTerms.filter((term) => term.relatedVenues.includes(venueId));
}
